# docker-compose.yml
sematext-agent:
  image: 'sematext/sematext-agent-docker:latest'
  environment:
    - LOGSENE_TOKEN=63d04666-5151-443b-84db-5ded5533ff7f
    - SPM_TOKEN=2c982fdf-bcaf-41e5-901f-fb9cc3b0b39b
    - affinity:container!=*sematext-agent*
  privileged: true
  restart: always
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
           
